name: Compile Drempels Executable
on:
  workflow_dispatch: 
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Get Source Code
      uses: actions/checkout@v4
    - name: Load Microsoft Build Tools
      uses: microsoft/setup-msbuild@v2
    - name: Compile Solution to Release
      run: |
        msbuild Drempels/Drempels.vcxproj /p:Configuration=Release /p:Platform=x64
    - name: Package Executable for Download
      uses: actions/upload-artifact@v4
      with:
        name: Drempels-Windows-x64
        path: |
          **/Release/*.exe
          **/Release/*.dll
